create_ip -name selectio_wiz -vendor xilinx.com -library ip -version 5.1 -module_name selectio_wiz_0
set_property -dict [list \
  CONFIG.USE_TEMPLATE {Custom} \
  CONFIG.BUS_DIR {OUTPUTS} \
  CONFIG.BUS_SIG_TYPE {DIFF} \
  CONFIG.BUS_IO_STD {TMDS_33} \
  CONFIG.SELIO_ACTIVE_EDGE {DDR} \
  CONFIG.USE_SERIALIZATION {true} \
  CONFIG.SERIALIZATION_FACTOR {10} \
  CONFIG.SYSTEM_DATA_WIDTH {3} \
  CONFIG.SELIO_CLK_BUF {MMCM} \
  CONFIG.CLK_FWD {true} \
  CONFIG.CLK_FWD_SER {true} \
  CONFIG.CONFIG_CLK_FWD {true} \
  CONFIG.SYSTEM_DATA_WIDTH {3} \
  CONFIG.SELIO_INTERFACE_TYPE {NETWORKING} \
  CONFIG.SELIO_BUS_IN_DELAY {NONE} \
  CONFIG.SELIO_CLK_SIG_TYPE {DIFF} \
  CONFIG.SELIO_CLK_IO_STD {TMDS_33} \
  CONFIG.CLK_FWD_SIG_TYPE {DIFF} \
  CONFIG.CLK_FWD_IO_STD {TMDS_33}] [get_ips selectio_wiz_0]

create_ip -name clk_wiz -vendor xilinx.com -library ip -version 6.0 -module_name vid_clk_gen
set_property -dict [list \
  CONFIG.USE_PHASE_ALIGNMENT {false} \
  CONFIG.JITTER_SEL {Min_O_Jitter} \
  CONFIG.PRIM_IN_FREQ {200.000} \
  CONFIG.CLKOUT2_USED {true} \
  CONFIG.CLK_OUT1_PORT {clk_tmds} \
  CONFIG.CLK_OUT2_PORT {clk_pix} \
  CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {692.5} \
  CONFIG.CLKOUT2_REQUESTED_OUT_FREQ {138.5} \
  CONFIG.USE_RESET {false} \
  CONFIG.SECONDARY_SOURCE {Single_ended_clock_capable_pin} \
  CONFIG.CLKIN1_JITTER_PS {50.0} \
  CONFIG.CLKOUT1_DRIVES {BUFG} \
  CONFIG.CLKOUT2_DRIVES {BUFG} \
  CONFIG.CLKOUT3_DRIVES {BUFG} \
  CONFIG.CLKOUT4_DRIVES {BUFG} \
  CONFIG.CLKOUT5_DRIVES {BUFG} \
  CONFIG.CLKOUT6_DRIVES {BUFG} \
  CONFIG.CLKOUT7_DRIVES {BUFG} \
  CONFIG.MMCM_DIVCLK_DIVIDE {5} \
  CONFIG.MMCM_BANDWIDTH {HIGH} \
  CONFIG.MMCM_CLKFBOUT_MULT_F {34.625} \
  CONFIG.MMCM_CLKIN1_PERIOD {5.000} \
  CONFIG.MMCM_CLKOUT0_DIVIDE_F {2.000} \
  CONFIG.MMCM_CLKOUT1_DIVIDE {10} \
  CONFIG.NUM_OUT_CLKS {2} \
  CONFIG.CLKOUT1_JITTER {92.728} \
  CONFIG.CLKOUT1_PHASE_ERROR {145.592} \
  CONFIG.CLKOUT2_JITTER {119.336} \
  CONFIG.CLKOUT2_PHASE_ERROR {145.592}] [get_ips vid_clk_gen]
