# Copyright lowRISC Contributors (COSMIC project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: "nix develop -c bash -e {0}"

    steps:
      - uses: actions/checkout@v5

      - name: License check
        uses: fsfe/reuse-action@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            substituters = https://nix-cache.lowrisc.org/public/ https://cache.nixos.org/
            trusted-public-keys = nix-cache.lowrisc.org-public-1:O6JLD0yXzaJDPiQW1meVu32JIDViuaPtGDfjlOopU7o= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

      - name: Prepare Nix environment
        run: |
          true

      - name: Generate software buildsystem
        run: |
          cmake -B build/sw -S sw

      - name: Lint - Clang Format
        run: |
          util/clang_format.py -i --dry-run -Werror

      - name: Lint - Clang Tidy
        run: |
          util/clang_tidy.py

      - name: Build software
        run: |
          cmake --build build/sw -j $(nproc)

      - name: Generate xbar
        run: |
          hw/vendor/lowrisc_ip/util/tlgen.py -t hw/top_chip/ip/xbar_peri/data/xbar_peri.hjson -o hw/top_chip/ip/xbar_peri

      - name: Build verilator
        run: |
          fusesoc --cores-root=. run --target=sim --tool=verilator --setup --build lowrisc:mocha:top_chip_system

      # Run the UART smoke test including simulation exit on the Verilator simulator.
      - name: Run smoke test
        run: |
          build/lowrisc_mocha_top_chip_system_0/sim-verilator/Vtop_chip_verilator -t -E build/sw/device/examples/hello_world/hello_world
